version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5443:5443
    environment:
      POSTGRES_USER: amr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: footforward
  test-db:
    image: postgres:13
    ports:
      - 5442:5442
    environment:
      POSTGRES_USER: amr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: footforward
