version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5111:5432
    environment:
      POSTGRES_USER: amr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: footforward
  test-db:
    image: postgres:13
    ports:
      - 5112:5432
    environment:
      POSTGRES_USER: amr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: footforward
